  - name: install vsftpd on emazon_ec2-serers
    yum: name=vsftpd state=latest
    when: ansible_os_family == 'RedHat'
    notify: start vsftpd

  - name: install vsftpd on ubuntu-servers
    apt: name=vsftpd state=latest
    when: ansible_os_family == "Debian"
    notify: start vsftpd
