- hosts: all
  vars:
    students:
         - Mark:
             city: Melbourne
             address: 0045-0987-8642
         - Angela:
             city: Sydney
             address: 3456-7685-9087
  tasks:
  - debug:
     var: students
